site_name: Open Idea
theme:
  logo: assets/open-idea-logo.png
  favicon: assets/open-idea-logo.png
  name: material
  palette:
    scheme: slate
    primary: green
  features:
    - navigation.indexes

nav:
  - Home: index.md
  - Ideas:
    - blog/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog:
      categories: true
      post_url_date_format: yyyy/MM/dd
  - search